//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        public int endereco_cod { get; set; }
        public int usuario_cod { get; set; }
        public string endereco_cep { get; set; }
        public string endereco_rua { get; set; }
        public string endereco_bairro { get; set; }
        public string endereco_cidade { get; set; }
        public string endereco_uf { get; set; }
        public string endereco_comp { get; set; }
        public string endereco_num { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
