//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealDelivery
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public grupo()
        {
            this.produto = new HashSet<produto>();
        }

        public long grupo_cod { get; set; }
        [DisplayName("Nome do Grupo")]
        public string grupo_nome { get; set; }
        [DisplayName("Ativo")]
        public string grupo_ativo { get; set; }
        [DisplayName("Descrição do Grupo")]
        public string grupo_desc { get; set; }
        [DisplayName("Imagem do Grupo")]
        public string grupo_img { get; set; }

        public HttpPostedFileBase img_grupo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produto> produto { get; set; }
    }
}
