//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_pedido
    {
        public int item_pedido_cod { get; set; }
        public int pedido_cod { get; set; }
        public int produto_cod { get; set; }
        public int item_pedido_qtd { get; set; }
        public float produto_valor { get; set; }
        public string produto_nome { get; set; }
    
        public virtual produto produto { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
