//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_perm
    {
        public int usuario_perm_cod { get; set; }
        public int usuario_cod { get; set; }
        public Nullable<int> usuario_nivel { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
