//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealDelivery
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.usuario_perm = new HashSet<usuario_perm>();
        }
    
        public int usuario_cod { get; set; }
        [DisplayName("E-mail")]
        public string usuario_email { get; set; }
        [DisplayName("Senha")]
        public string usuario_senha { get; set; }
        [DisplayName("Nome")]
        public string usuario_nome { get; set; }
        [DisplayName("Telefone")]
        public string usuario_cel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_perm> usuario_perm { get; set; }
    }
}
